[package]
name = "jsondif"
version = "0.1.0"
edition = "2021"
authors = ["Benlukka"]
description = "Displays the difference between two json files using Rust"

[dependencies]
json = "0.12.4"
chksum = "0.4.0"
log = "0.4.26"
colored = "3.0.0"
serde_json = "1.0.139"
lincolns = "0.1"
